services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      target: local
      args:
        ENV: local
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 80



    