services:
  web:
    container_name: web
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        ENV: dev
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
