services:

  # object storage
  minio:
    hostname: minio
    container_name: minio
    image: minio/minio
    platform: linux/arm64
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./docker/data/minio:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server /data --console-address ":9001"




